//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c:/Users/tomonaga/Documents/GitHub/YAMAGoya/resource/SigmaCondition.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="SigmaConditionParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public interface ISigmaConditionListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by the <c>AndExpr</c>
	/// labeled alternative in <see cref="SigmaConditionParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAndExpr([NotNull] SigmaConditionParser.AndExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>AndExpr</c>
	/// labeled alternative in <see cref="SigmaConditionParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAndExpr([NotNull] SigmaConditionParser.AndExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>IdentifierExpr</c>
	/// labeled alternative in <see cref="SigmaConditionParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIdentifierExpr([NotNull] SigmaConditionParser.IdentifierExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>IdentifierExpr</c>
	/// labeled alternative in <see cref="SigmaConditionParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIdentifierExpr([NotNull] SigmaConditionParser.IdentifierExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ParensExpr</c>
	/// labeled alternative in <see cref="SigmaConditionParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParensExpr([NotNull] SigmaConditionParser.ParensExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ParensExpr</c>
	/// labeled alternative in <see cref="SigmaConditionParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParensExpr([NotNull] SigmaConditionParser.ParensExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>CountExpr</c>
	/// labeled alternative in <see cref="SigmaConditionParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCountExpr([NotNull] SigmaConditionParser.CountExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>CountExpr</c>
	/// labeled alternative in <see cref="SigmaConditionParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCountExpr([NotNull] SigmaConditionParser.CountExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>NotExpr</c>
	/// labeled alternative in <see cref="SigmaConditionParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNotExpr([NotNull] SigmaConditionParser.NotExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>NotExpr</c>
	/// labeled alternative in <see cref="SigmaConditionParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNotExpr([NotNull] SigmaConditionParser.NotExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>AllOfThemExpr</c>
	/// labeled alternative in <see cref="SigmaConditionParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAllOfThemExpr([NotNull] SigmaConditionParser.AllOfThemExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>AllOfThemExpr</c>
	/// labeled alternative in <see cref="SigmaConditionParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAllOfThemExpr([NotNull] SigmaConditionParser.AllOfThemExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>OrExpr</c>
	/// labeled alternative in <see cref="SigmaConditionParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOrExpr([NotNull] SigmaConditionParser.OrExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>OrExpr</c>
	/// labeled alternative in <see cref="SigmaConditionParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOrExpr([NotNull] SigmaConditionParser.OrExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SigmaConditionParser.count_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCount_expr([NotNull] SigmaConditionParser.Count_exprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SigmaConditionParser.count_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCount_expr([NotNull] SigmaConditionParser.Count_exprContext context);
}
